---
default:
  image: node:18-alpine
  before_script:
    - npm install --cache .npm --frozen-lockfile --prefer-offline
  cache:
    - key: npm
      paths:
        - .npm/
    - key:
        files:
          - package-lock.json
      paths:
        - node_modules/

lint:
  stage: test
  script:
    - npm run lint

test:
  stage: test
  variables:
    POSTGRES_USER: gitlab-ci
    POSTGRES_PASSWORD: password
    POSTGRES_DB: testdb
  services:
    - postgres:15-alpine
  script:
    - export POSTGRES_URL_NON_POOLING="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"
    - export POSTGRES_PRISMA_URL="$POSTGRES_URL_NON_POOLING"
    - npx prisma migrate deploy
    - npm test
  artifacts:
    when: always
    reports:
      junit: junit.xml

deploy_preview:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
  script:
    - npx gulp deploy:preview
  artifacts:
    reports:
      dotenv: deploy.env
  environment:
    name: preview-$CI_COMMIT_REF_SLUG/$CI_COMMIT_SHORT_SHA
    url: $DEPLOYMENT_URL

deploy_production:
  stage: deploy
  resource_group: production
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - npx gulp deploy:production
  environment:
    name: production
    url: $PRODUCTION_URL
