#!/bin/sh -eux

ENVIRONMENT="$1"

if [[ "$ENVIRONMENT" = "production" ]]; then
    PROD=--prod
else
    PROD=
fi

npx vercel pull --token="$VERCEL_TOKEN" --yes --environment="$ENVIRONMENT"
npx expo export:web
ln -sfT web-build public
npx vercel build $PROD

DEPLOYMENT_URL="$(npx vercel deploy --token="$VERCEL_TOKEN" $PROD --prebuilt)"

printf "DEPLOYMENT_URL=%s\n" "$DEPLOYMENT_URL" > deploy.env
